# Generated by Django 3.2.9 on 2021-12-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='value',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
