# Generated by Django 3.2.9 on 2021-12-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0002_alter_sitesetting_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='value',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
